CC_EXEC = g++
CC_FLASGS = -c

CC = ${CC_EXEC} ${CC_FLASGS}

BUILD_DR = build


all: a.out


a.out: main.o 


main.o: main.cpp
	${CC} main.cpp -o ${BUILD_DR}/main.o


clean:
	rm -rf build/ && mkdir -p build